// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PhoneWeb.Data;

namespace PhoneWeb.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20201203174344_InitData")]
    partial class InitData
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedName")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles");

                    b.HasData(
                        new
                        {
                            Id = "38a91b1a-d324-4ae1-9c95-fcdbf2d39825",
                            ConcurrencyStamp = "02dcecf5-513b-4a85-9625-2570fc4830d9",
                            Name = "Visitor",
                            NormalizedName = "VISITOR"
                        },
                        new
                        {
                            Id = "b324255c-902a-472d-87d0-0f20f40c14d3",
                            ConcurrencyStamp = "89515eed-de79-47e0-8542-dbd68d1cc890",
                            Name = "Administrator",
                            NormalizedName = "ADMINISTRATOR"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens");
                });

            modelBuilder.Entity("PhoneWeb.Models.Domain.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CategoryId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            CategoryName = "Iphone"
                        },
                        new
                        {
                            CategoryId = 2,
                            CategoryName = "SamSung"
                        },
                        new
                        {
                            CategoryId = 3,
                            CategoryName = "Vsmart"
                        },
                        new
                        {
                            CategoryId = 4,
                            CategoryName = "Nokia"
                        },
                        new
                        {
                            CategoryId = 5,
                            CategoryName = "Oppo"
                        },
                        new
                        {
                            CategoryId = 6,
                            CategoryName = "Xiaomi"
                        },
                        new
                        {
                            CategoryId = 7,
                            CategoryName = "Huawei"
                        },
                        new
                        {
                            CategoryId = 8,
                            CategoryName = "Vivo"
                        },
                        new
                        {
                            CategoryId = 9,
                            CategoryName = "LG"
                        });
                });

            modelBuilder.Entity("PhoneWeb.Models.Domain.Order", b =>
                {
                    b.Property<int>("OrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("DiaChiGiaoHang")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("SoDienThoai")
                        .IsRequired()
                        .HasColumnType("nvarchar(10)")
                        .HasMaxLength(10);

                    b.Property<string>("TenKhachHang")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("OrderId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("PhoneWeb.Models.Domain.OrderDetail", b =>
                {
                    b.Property<int>("OrderDetailId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("OrderDetailId");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.ToTable("OrderDetails");
                });

            modelBuilder.Entity("PhoneWeb.Models.Domain.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descriptions")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProductImage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("ProductPrice")
                        .HasColumnType("float");

                    b.Property<int>("ProductQuantity")
                        .HasColumnType("int");

                    b.HasKey("ProductId");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ProductId = 1,
                            CategoryId = 1,
                            CreateDate = new DateTime(2020, 12, 4, 0, 43, 44, 215, DateTimeKind.Local).AddTicks(4729),
                            Descriptions = "Công nghệ màn hình: OLED, Độ phân giải: 1242 x 2688 Pixels, Màn hình rộng: 6.5 inch, Mặt kính cảm ứng: Kính cường lực oleophobic(ion cường lực), Camera sau: Độ phân giải 3 camera 12 MP, Camera trước: 12 MP, Ram: 4GB, Bộ nhớ trong: 64GB, Không hổ trợ bộ nhớ ngoàiDung lượng pin 3969 mAh",
                            ProductImage = "ip11.jpg",
                            ProductName = "Iphone11",
                            ProductPrice = 20000000.0,
                            ProductQuantity = 100
                        },
                        new
                        {
                            ProductId = 2,
                            CategoryId = 1,
                            CreateDate = new DateTime(2020, 12, 4, 0, 43, 44, 216, DateTimeKind.Local).AddTicks(5258),
                            Descriptions = "Công nghệ màn hình: OLED, Độ phân giải: 1125 x 2436 Pixels, Màn hình rộng: 5.8 inch, Mặt kính cảm ứng: Kính cường lực oleophobic(ion cường lực), Camera sau: Chính 12 MP & Phụ 12 MP, Camera trước: 7 MP, Ram: 3GB, Bộ nhớ trong: 64GB, Không hổ trợ bộ nhớ ngoàiDung lượng pin 2716 mAh",
                            ProductImage = "ipx.jpg",
                            ProductName = "Iphone X",
                            ProductPrice = 17500000.0,
                            ProductQuantity = 100
                        },
                        new
                        {
                            ProductId = 3,
                            CategoryId = 1,
                            CreateDate = new DateTime(2020, 12, 4, 0, 43, 44, 216, DateTimeKind.Local).AddTicks(5303),
                            Descriptions = "Công nghệ màn hình: LED-backlit IPS LCD, Độ phân giải: Full HD (1080 x 1920 Pixels), Màn hình rộng: 5.5 inch, Mặt kính cảm ứng: Kính cường lực oleophobic(ion cường lực), Camera sau: Chính 12 MP & Phụ 12 MP, Camera trước: 7 MP, Ram: 3GB, Bộ nhớ trong: 64GB, Không hổ trợ bộ nhớ ngoàiDung lượng pin 2691 mAh",
                            ProductImage = "ip8.jpg",
                            ProductName = "Iphone8",
                            ProductPrice = 14000000.0,
                            ProductQuantity = 100
                        },
                        new
                        {
                            ProductId = 4,
                            CategoryId = 2,
                            CreateDate = new DateTime(2020, 12, 4, 0, 43, 44, 216, DateTimeKind.Local).AddTicks(5307),
                            Descriptions = "Công nghệ màn hình: Màn hình 6.7, Quad HD+ (2K+)Độ phân giải: 2K+ (1440 x 3200 Pixels), Hệ điều hành: Android 10, Mặt kính cảm ứng: 	Kính cường lực Corning Gorilla Glass 6, Camera sau: Chính 12 MP & phụ 64 MP, 12 MP, TOF 3D, Camera trước: 10 MP, Ram: 8 GB, Bộ nhớ trong: 128GB, Hổ trợ bộ nhớ ngoài tối đa 1TBDung lượng pin 4500 mAh",
                            ProductImage = "ss20.jpg",
                            ProductName = "Samsung Galaxy S20+",
                            ProductPrice = 18990000.0,
                            ProductQuantity = 100
                        },
                        new
                        {
                            ProductId = 5,
                            CategoryId = 3,
                            CreateDate = new DateTime(2020, 12, 4, 0, 43, 44, 216, DateTimeKind.Local).AddTicks(5309),
                            Descriptions = "Công nghệ màn hình: IPS LCD, Độ phân giải: HD+ (720 x 1600 Pixels), Màn hình rộng: 6.5 inch, Mặt kính cảm ứng: 	Mặt kính cong 2.5D, Camera sau: Chính 13 MP & Phụ 8 MP, 2 MP, Camera trước: 8 MP, Ram: 4 GB, Bộ nhớ trong: 64 GB, Hổ trợ bộ nhớ ngoài tối đa 64GBDung lượng pin 5000 mAh",
                            ProductImage = "vsmartjoy3.jpg",
                            ProductName = "Vsmart Joy 3",
                            ProductPrice = 4000000.0,
                            ProductQuantity = 100
                        },
                        new
                        {
                            ProductId = 6,
                            CategoryId = 4,
                            CreateDate = new DateTime(2020, 12, 4, 0, 43, 44, 216, DateTimeKind.Local).AddTicks(5311),
                            Descriptions = "Nokia 1280 - Legendary, Nghe, Gọi, Nhắn tin, Thay thế đồng hồ báo thức, Chống nước, Chống sốc",
                            ProductImage = "nokia1280.jpg",
                            ProductName = "Nokia 1280",
                            ProductPrice = 200000.0,
                            ProductQuantity = 100
                        },
                        new
                        {
                            ProductId = 7,
                            CategoryId = 3,
                            CreateDate = new DateTime(2020, 12, 4, 0, 43, 44, 216, DateTimeKind.Local).AddTicks(5313),
                            Descriptions = "Công nghệ màn hình: AMOLED, Độ phân giải: Full HD+ (1080 x 2232 Pixels), Màn hình rộng: 6.2 inch, Mặt kính cảm ứng: Mặt kính cong 2.5D, Camera sau: Chính 48 MP & Phụ 8 MP, 5 MP, Camera trước: 20 MP, Ram: 6 GB, Bộ nhớ trong: 64 GB, Không hổ trợ bộ nhớ ngoài Dung lượng pin 4000 mAh",
                            ProductImage = "vslive.jpg",
                            ProductName = "Vsmart Live",
                            ProductPrice = 7000000.0,
                            ProductQuantity = 100
                        },
                        new
                        {
                            ProductId = 8,
                            CategoryId = 2,
                            CreateDate = new DateTime(2020, 12, 4, 0, 43, 44, 216, DateTimeKind.Local).AddTicks(5315),
                            Descriptions = "Công nghệ màn hình: Dynamic AMOLED 2X, 6.2 inch, Quad HD+ (2K+), Độ phân giải: Full HD+ (1080 x 2400 Pixels), Màn hình rộng: 6.2 inch, Mặt kính cảm ứng: Kính cường lực Corning Gorilla Glass 6, Camera sau: Chính 12 MP & Phụ 64 MP, 12 MP, Camera trước: 10 MP, Ram: 8 GB, Bộ nhớ trong: 128 GB, Hổ trợ bộ nhớ ngoài tối đa 512 GB Thẻ Sim: 2 Nano SIM hoặc 1 Nano SIM + 1 eSIM, Hỗ trợ 4GDung lượng pin 4000 mAhCông nghệ pin: Sạc ngược không dây, Sạc pin nhanh, Siêu tiết kiệm pin, Sạc không dây ",
                            ProductImage = "ssS20.jpg",
                            ProductName = "Samsung Galaxy S20",
                            ProductPrice = 21490000.0,
                            ProductQuantity = 100
                        },
                        new
                        {
                            ProductId = 9,
                            CategoryId = 2,
                            CreateDate = new DateTime(2020, 12, 4, 0, 43, 44, 216, DateTimeKind.Local).AddTicks(5317),
                            Descriptions = "Công nghệ màn hình: PLS TFT LCD, Độ phân giải: 	Full HD+ (1080 x 2340 Pixels), Màn hình rộng: 6.3 inch, Mặt kính cảm ứng: 	Mặt kính cong 2.5D, Camera sau: 	Chính 13 MP & Phụ 5 MP, Camera trước: 8 MP, Ram: 3 GB, Bộ nhớ trong: 31 GB, Hổ trợ bộ nhớ ngoài tối đa 512 GB Dung lượng pin 4000 mAh",
                            ProductImage = "ssM20.png",
                            ProductName = "Samsung Galaxy M20",
                            ProductPrice = 5490000.0,
                            ProductQuantity = 100
                        },
                        new
                        {
                            ProductId = 10,
                            CategoryId = 2,
                            CreateDate = new DateTime(2020, 12, 4, 0, 43, 44, 216, DateTimeKind.Local).AddTicks(5319),
                            Descriptions = "Công nghệ màn hình: Super AMOLED, Độ phân giải: 	Full HD+ (1080 x 2400 Pixels), Màn hình rộng: 6.7 inch, Mặt kính cảm ứng: 	Kính cường lực, Camera sau: Chính 64 MP & Phụ 12 MP, 5 MP, 5 MP, Camera trước: 32 MP, Ram: 8 GB, Bộ nhớ trong: 128 GB, Hổ trợ bộ nhớ ngoài tối đa 512 GB Dung lượng pin 5000 mAh",
                            ProductImage = "ssA71.png",
                            ProductName = "Samsung Galaxy A71",
                            ProductPrice = 10590000.0,
                            ProductQuantity = 100
                        },
                        new
                        {
                            ProductId = 11,
                            CategoryId = 4,
                            CreateDate = new DateTime(2020, 12, 4, 0, 43, 44, 216, DateTimeKind.Local).AddTicks(5321),
                            Descriptions = "Công nghệ màn hình: IPS LCD, Độ phân giải: 	Full HD+ (1080 x 2340 Pixels), Màn hình rộng: 6.3 inch, Mặt kính cảm ứng: 	Kính cường lực Corning Gorilla Glass 3, Camera sau: Chính 48 MP & Phụ 8 MP, 5 MP, Camera trước: 20 MP, Ram: 4 GB, Bộ nhớ trong: 64 GB, Hổ trợ bộ nhớ ngoài tối đa 400 GB Dung lượng pin 4500 mAh",
                            ProductImage = "nokia72.png",
                            ProductName = "Nokia 7.2",
                            ProductPrice = 6190000.0,
                            ProductQuantity = 100
                        },
                        new
                        {
                            ProductId = 12,
                            CategoryId = 2,
                            CreateDate = new DateTime(2020, 12, 4, 0, 43, 44, 216, DateTimeKind.Local).AddTicks(5328),
                            Descriptions = "Công nghệ màn hình: Super AMOLED, Độ phân giải: 	Full HD+ (1080 x 2340 Pixels), Màn hình rộng: 6.4 inch, Mặt kính cảm ứng: 	Mặt kính cong 2.5D, Camera sau: Chính 48 MP & Phụ 8 MP, 5 MP, Camera trước: 32 MP, Ram: 4 GB, Bộ nhớ trong: 64 GB, Hổ trợ bộ nhớ ngoài tối đa 512 GB Dung lượng pin 4000 mAh",
                            ProductImage = "ssA50s.png",
                            ProductName = "Samsung Galaxy A50s",
                            ProductPrice = 6990000.0,
                            ProductQuantity = 100
                        },
                        new
                        {
                            ProductId = 13,
                            CategoryId = 3,
                            CreateDate = new DateTime(2020, 12, 4, 0, 43, 44, 216, DateTimeKind.Local).AddTicks(5330),
                            Descriptions = "Công nghệ màn hình: AMOLED, Độ phân giải: Full HD+ (1080 x 2340 Pixels), Màn hình rộng: 6.39 inch, Mặt kính cảm ứng: Mặt kính cong 2.5D, Camera sau: Chính 48 MP & Phụ 8 MP, 5 MP, Camera trước: 16 MP, Ram: 6 GB, Bộ nhớ trong: 64 GB, Hổ trợ bộ nhớ ngoài tối đa 256GB Dung lượng pin 4020 mAh",
                            ProductImage = "vsActive3.jpg",
                            ProductName = "Vsmart Active 3",
                            ProductPrice = 3790000.0,
                            ProductQuantity = 100
                        },
                        new
                        {
                            ProductId = 14,
                            CategoryId = 3,
                            CreateDate = new DateTime(2020, 12, 4, 0, 43, 44, 216, DateTimeKind.Local).AddTicks(5333),
                            Descriptions = "Công nghệ màn hình: IPS LCD, Độ phân giải: HD+ (720 x 1520 Pixels), Màn hình rộng: 5.7 inch, Mặt kính cảm ứng: Mặt kính cong 2.5D, Camera sau: Chính 8 MP & Phụ 2 MP, Camera trước: 5 MP, Ram: 2 GB, Bộ nhớ trong: 16 GB, Hổ trợ bộ nhớ ngoài tối đa 256GB Dung lượng pin 3000 mAh",
                            ProductImage = "vsStar.jpg",
                            ProductName = "Vsmart Star",
                            ProductPrice = 1390000.0,
                            ProductQuantity = 100
                        },
                        new
                        {
                            ProductId = 15,
                            CategoryId = 3,
                            CreateDate = new DateTime(2020, 12, 4, 0, 43, 44, 216, DateTimeKind.Local).AddTicks(5335),
                            Descriptions = "Công nghệ màn hình: IPS LCD, Độ phân giải: HD+ (720 x 1440 Pixels), Màn hình rộng: 6.0 inch, Mặt kính cảm ứng: Mặt kính cong 2.5D, Camera sau: Chính 8 MP, Camera trước: 5 MP, Ram: 2 GB, Bộ nhớ trong: 16 GB, Hổ trợ bộ nhớ ngoài tối đa 64GB Dung lượng pin 3000 mAh",
                            ProductImage = "vsBee.jpg",
                            ProductName = "Vsmart Bee",
                            ProductPrice = 1000000.0,
                            ProductQuantity = 100
                        },
                        new
                        {
                            ProductId = 16,
                            CategoryId = 5,
                            CreateDate = new DateTime(2020, 12, 4, 0, 43, 44, 216, DateTimeKind.Local).AddTicks(5336),
                            Descriptions = "Công nghệ màn hình: AMOLED, Độ phân giải: Full HD+ (1080 x 2400 Pixels), Màn hình rộng: 6.4 inch, Mặt kính cảm ứng: Kính cường lực Corning Gorilla Glass 5, Camera sau: Chính 48 MP & Phụ 13 MP, 8 MP, 2 MP, Camera trước: 44 MP, Ram: 8 GB, Bộ nhớ trong: 128 GB, Hổ trợ bộ nhớ ngoài tối đa 256GB Dung lượng pin 4025 mAh",
                            ProductImage = "oppoReno3.png",
                            ProductName = "OPPO Reno3",
                            ProductPrice = 8490000.0,
                            ProductQuantity = 100
                        },
                        new
                        {
                            ProductId = 17,
                            CategoryId = 5,
                            CreateDate = new DateTime(2020, 12, 4, 0, 43, 44, 216, DateTimeKind.Local).AddTicks(5338),
                            Descriptions = "Công nghệ màn hình: AMOLED, Độ phân giải: Full HD+ (1080 x 2400 Pixels), Màn hình rộng: 6.4 inch, Mặt kính cảm ứng: Kính cường lực Corning Gorilla Glass 5, Camera sau: Chính 48 MP & Phụ 13 MP, 8 MP, 2 MP, Camera trước: 16 MP, Ram: 8 GB, Bộ nhớ trong: 128 GB, Hổ trợ bộ nhớ ngoài tối đa 256GB Dung lượng pin 4025 mAh",
                            ProductImage = "oppoA91.jpg",
                            ProductName = "OPPO A91",
                            ProductPrice = 5990000.0,
                            ProductQuantity = 100
                        },
                        new
                        {
                            ProductId = 18,
                            CategoryId = 5,
                            CreateDate = new DateTime(2020, 12, 4, 0, 43, 44, 216, DateTimeKind.Local).AddTicks(5340),
                            Descriptions = "Công nghệ màn hình: AMOLED, Độ phân giải: 2K+ (1440 x 3168 Pixels), Màn hình rộng: 6.78 inch, Mặt kính cảm ứng: Kính cường lực Corning Gorilla Glass 6, Camera sau: Chính 48 MP & Phụ 13 MP, 12 MP, Camera trước: 32 MP, Ram: 12 GB, Bộ nhớ trong: 256 GB, Không hổ trợ bộ nhớ ngoàiDung lượng pin 4200 mAh",
                            ProductImage = "oppoFindx2.png",
                            ProductName = "OPPO Find X2",
                            ProductPrice = 23990000.0,
                            ProductQuantity = 100
                        },
                        new
                        {
                            ProductId = 19,
                            CategoryId = 5,
                            CreateDate = new DateTime(2020, 12, 4, 0, 43, 44, 216, DateTimeKind.Local).AddTicks(5342),
                            Descriptions = "Công nghệ màn hình: IPS LCD, Độ phân giải: HD+ (720 x 1600 Pixels), Màn hình rộng: 6.5 inch, Mặt kính cảm ứng: Mặt kính cong 2.5D, Camera sau: Chính 12 MP & Phụ 2 MP, 2 MP, Camera trước: 8 MP, Ram: 6 GB, Bộ nhớ trong: 128 GB, Hổ trợ bộ nhớ ngoài tối đa 256GBDung lượng pin 4230 mAh",
                            ProductImage = "oppoA31.png",
                            ProductName = "OPPO A31",
                            ProductPrice = 4990000.0,
                            ProductQuantity = 100
                        },
                        new
                        {
                            ProductId = 20,
                            CategoryId = 4,
                            CreateDate = new DateTime(2020, 12, 4, 0, 43, 44, 216, DateTimeKind.Local).AddTicks(5344),
                            Descriptions = "Công nghệ màn hình: 	TFT, Độ phân giải: HD+ (720 x 1520 Pixels), Màn hình rộng: 6.2 inch, Mặt kính cảm ứng: Mặt kính cong 2.5D, Camera sau: Chính 13 MP & Phụ 2 MP, Camera trước: 5 MP, Ram: 2 GB, Bộ nhớ trong: 32 GB, Hổ trợ bộ nhớ ngoài tối đa 512GBDung lượng pin 4000 mAh",
                            ProductImage = "nokia2.3.jpeg",
                            ProductName = "Nokia 2.3",
                            ProductPrice = 2290000.0,
                            ProductQuantity = 100
                        },
                        new
                        {
                            ProductId = 21,
                            CategoryId = 2,
                            CreateDate = new DateTime(2020, 12, 4, 0, 43, 44, 216, DateTimeKind.Local).AddTicks(5346),
                            Descriptions = "Công nghệ màn hình: 	TFT, Độ phân giải: HD+ (720 x 1520 Pixels), Màn hình rộng: 6.2 inch, Mặt kính cảm ứng: Mặt kính cong 2.5D, Camera sau: Chính 13 MP & Phụ 2 MP, Camera trước: 5 MP, Ram: 2 GB, Bộ nhớ trong: 32 GB, Hổ trợ bộ nhớ ngoài tối đa 512GBDung lượng pin 4000 mAh",
                            ProductImage = "ssA21.png",
                            ProductName = "SamSung Galaxy A21s",
                            ProductPrice = 5690000.0,
                            ProductQuantity = 100
                        },
                        new
                        {
                            ProductId = 22,
                            CategoryId = 2,
                            CreateDate = new DateTime(2020, 12, 4, 0, 43, 44, 216, DateTimeKind.Local).AddTicks(5348),
                            Descriptions = "Công nghệ màn hình: 	TFT, Độ phân giải: HD+ (720 x 1520 Pixels), Màn hình rộng: 6.2 inch, Mặt kính cảm ứng: Mặt kính cong 2.5D, Camera sau: Chính 13 MP & Phụ 2 MP, Camera trước: 5 MP, Ram: 2 GB, Bộ nhớ trong: 32 GB, Hổ trợ bộ nhớ ngoài tối đa 512GBDung lượng pin 4000 mAh",
                            ProductImage = "ssA80.png",
                            ProductName = "SamSung Galaxy A80",
                            ProductPrice = 8990000.0,
                            ProductQuantity = 100
                        },
                        new
                        {
                            ProductId = 23,
                            CategoryId = 2,
                            CreateDate = new DateTime(2020, 12, 4, 0, 43, 44, 216, DateTimeKind.Local).AddTicks(5350),
                            Descriptions = "Công nghệ màn hình: 	TFT, Độ phân giải: HD+ (720 x 1520 Pixels), Màn hình rộng: 6.2 inch, Mặt kính cảm ứng: Mặt kính cong 2.5D, Camera sau: Chính 13 MP & Phụ 2 MP, Camera trước: 5 MP, Ram: 2 GB, Bộ nhớ trong: 32 GB, Hổ trợ bộ nhớ ngoài tối đa 512GBDung lượng pin 4000 mAh",
                            ProductImage = "ssZFlip.png",
                            ProductName = "SamSung Galaxy Z Flip",
                            ProductPrice = 36000000.0,
                            ProductQuantity = 100
                        },
                        new
                        {
                            ProductId = 24,
                            CategoryId = 2,
                            CreateDate = new DateTime(2020, 12, 4, 0, 43, 44, 216, DateTimeKind.Local).AddTicks(5351),
                            Descriptions = "Công nghệ màn hình: PLS TFT , Độ phân giải: 	Full HD+ (720 x 1520 Pixels), Màn hình rộng: 6.2 inch, Mặt kính cảm ứng: 	Mặt kính cong 2.5D, Camera sau: 	Chính 13 MP & Phụ 5 MP, Camera trước: 8 MP, Ram: 2 GB, Bộ nhớ trong: 32 GB, Hổ trợ bộ nhớ ngoài tối đa 512 GB Dung lượng pin 4000 mAh",
                            ProductImage = "SsA10.jpg",
                            ProductName = "Samsung Galaxy A10",
                            ProductPrice = 3690000.0,
                            ProductQuantity = 100
                        },
                        new
                        {
                            ProductId = 25,
                            CategoryId = 6,
                            CreateDate = new DateTime(2020, 12, 4, 0, 43, 44, 216, DateTimeKind.Local).AddTicks(5353),
                            Descriptions = "Công nghệ màn hình: IPS LCD, Độ phân giải: 	Full HD+ (1080 x 2340 Pixels), Màn hình rộng: 6.53 inch, Mặt kính cảm ứng: 	Kính cường lực Corning Gorilla Glass 3, Camera sau: 	Chính 13 MP & Phụ 8 MP, 5MP, 2MP, Camera trước: 20 MP, Ram: 8 GB, Bộ nhớ trong: 256 GB, Hổ trợ bộ nhớ ngoài tối đa 512 GB Dung lượng pin 5000 mAh",
                            ProductImage = "XmR9.jpg",
                            ProductName = "Xiaomi Redmi 9",
                            ProductPrice = 3790000.0,
                            ProductQuantity = 100
                        },
                        new
                        {
                            ProductId = 26,
                            CategoryId = 6,
                            CreateDate = new DateTime(2020, 12, 4, 0, 43, 44, 216, DateTimeKind.Local).AddTicks(5355),
                            Descriptions = "Công nghệ màn hình: ILS LCD, Độ phân giải: 	Full HD+ (1080 x 2340 Pixels), Màn hình rộng: 6.53 inch, Mặt kính cảm ứng: 	Kính cường lực Corning Gorilla Glass 5, Camera sau: 	Chính 108 MP & Phụ 13 MP, 5MP, Camera trước: 13 MP, Ram: 4 GB, Bộ nhớ trong: 128 GB, Hổ trợ bộ nhớ ngoài tối đa 512 GB Dung lượng pin 5020 mAh",
                            ProductImage = "XmN9.jpg",
                            ProductName = "Xiaomi Redmi Note 9",
                            ProductPrice = 4790000.0,
                            ProductQuantity = 100
                        },
                        new
                        {
                            ProductId = 27,
                            CategoryId = 6,
                            CreateDate = new DateTime(2020, 12, 4, 0, 43, 44, 216, DateTimeKind.Local).AddTicks(5357),
                            Descriptions = "Công nghệ màn hình: ILS LCD, Độ phân giải: 	Full HD+ (1080 x 2440 Pixels), Màn hình rộng: 6.53 inch, Mặt kính cảm ứng: 	Kính cường lực Corning Gorilla Glass 5, Camera sau: 	Chính 48 MP & Phụ 8 MP, 2MP, 2MP Camera trước: 13 MP, Ram: 4 GB, Bộ nhớ trong: 128 GB, Hổ trợ bộ nhớ ngoài tối đa 512 GB Dung lượng pin 5020 mAh",
                            ProductImage = "Xm10T.png",
                            ProductName = "Xiaomi Mi 10T",
                            ProductPrice = 12990000.0,
                            ProductQuantity = 100
                        },
                        new
                        {
                            ProductId = 28,
                            CategoryId = 6,
                            CreateDate = new DateTime(2020, 12, 4, 0, 43, 44, 216, DateTimeKind.Local).AddTicks(5359),
                            Descriptions = "Công nghệ màn hình: IPS LCD, Độ phân giải: 	Full HD+ (1080 x 2400 Pixels), Màn hình rộng: 6.67 inch, Mặt kính cảm ứng: 	Kính cường lực Corning Gorilla Glass 5, Camera sau: 	Chính 64 MP & Phụ 13 MP, 2MP, 2MP, Camera trước: 20 MP, Ram: 6 GB, Bộ nhớ trong: 128 GB, Hổ trợ bộ nhớ ngoài tối đa 256 GB Dung lượng pin 5160 mAh",
                            ProductImage = "XPX3.jpg",
                            ProductName = "Xiaomi POCO X3 NFC",
                            ProductPrice = 6990000.0,
                            ProductQuantity = 100
                        },
                        new
                        {
                            ProductId = 29,
                            CategoryId = 6,
                            CreateDate = new DateTime(2020, 12, 4, 0, 43, 44, 216, DateTimeKind.Local).AddTicks(5360),
                            Descriptions = "Công nghệ màn hình: IPS LCD, Độ phân giải: 	Full HD+ (1080 x 2400 Pixels), Màn hình rộng: 6.67 inch, Mặt kính cảm ứng: 	Kính cường lực Corning Gorilla Glass 5, Camera sau: 	Chính 48 MP & Phụ 8 MP, 5MP, 2MP, Camera trước: 16 MP, Ram: 6 GB, Bộ nhớ trong: 128 GB, Hổ trợ bộ nhớ ngoài tối đa 256 GB Dung lượng pin 5020 mAh",
                            ProductImage = "XRN9S.jpg",
                            ProductName = "Xiaomi Redmi Note 9S",
                            ProductPrice = 5690000.0,
                            ProductQuantity = 100
                        },
                        new
                        {
                            ProductId = 30,
                            CategoryId = 7,
                            CreateDate = new DateTime(2020, 12, 4, 0, 43, 44, 216, DateTimeKind.Local).AddTicks(5362),
                            Descriptions = "Công nghệ màn hình: LTPS LCD, Độ phân giải: 	Full HD+ (720 x 1600 Pixels), Màn hình rộng: 6.4 inch, Mặt kính cảm ứng: 	Mặt kính cong 2.5D, Camera sau: 	Chính 13 MP & Phụ 5 MP, 2MP, Camera trước: 8 MP, Ram: 4 GB, Bộ nhớ trong: 64 GB, Hổ trợ bộ nhớ ngoài tối đa 256 GB Dung lượng pin 5000 mAh",
                            ProductImage = "HN7.jpg",
                            ProductName = "Huawei Nova 7i",
                            ProductPrice = 3340000.0,
                            ProductQuantity = 100
                        },
                        new
                        {
                            ProductId = 31,
                            CategoryId = 7,
                            CreateDate = new DateTime(2020, 12, 4, 0, 43, 44, 216, DateTimeKind.Local).AddTicks(5450),
                            Descriptions = "Công nghệ màn hình: IPS LCD, Độ phân giải: 	Full HD+ (1080 x 2310 Pixels), Màn hình rộng: 6.3 inch, Mặt kính cảm ứng: 	Mặt kính cong 2.5D, Camera sau: 	Chính 48 MP & Phụ 8 MP, 2MP, 2MP, Camera trước: 16 MP, Ram: 8 GB, Bộ nhớ trong: 128 GB, Hổ trợ bộ nhớ ngoài tối đa 256 GB Dung lượng pin 4200 mAh",
                            ProductImage = "HY6.png",
                            ProductName = "Huawei Y6p",
                            ProductPrice = 5990000.0,
                            ProductQuantity = 100
                        },
                        new
                        {
                            ProductId = 32,
                            CategoryId = 7,
                            CreateDate = new DateTime(2020, 12, 4, 0, 43, 44, 216, DateTimeKind.Local).AddTicks(5453),
                            Descriptions = "Công nghệ màn hình: OLED, Độ phân giải: 	Full HD+ (1080 x 2340 Pixels), Màn hình rộng: 6.3 inch, Mặt kính cảm ứng: 	Mặt kính cong 2.5D, Camera sau: 	Chính 40 MP & Phụ 20 MP, 8MP, Camera trước: 32 MP, Ram: 8 GB, Bộ nhớ trong: 256 GB, Hổ trợ bộ nhớ ngoài tối đa 512 GB Dung lượng pin 4200 mAh",
                            ProductImage = "HP30Pro.jpg",
                            ProductName = "Huawei P30 Pro",
                            ProductPrice = 13990000.0,
                            ProductQuantity = 100
                        },
                        new
                        {
                            ProductId = 33,
                            CategoryId = 7,
                            CreateDate = new DateTime(2020, 12, 4, 0, 43, 44, 216, DateTimeKind.Local).AddTicks(5455),
                            Descriptions = "Công nghệ màn hình: LTPS, Độ phân giải: 	Full HD+ (1080 x 2340 Pixels), Màn hình rộng: 6.26 inch, Mặt kính cảm ứng: 	Mặt kính cong 3D, Camera sau: 	Chính 48 MP & Phụ 16 MP, 2MP, 2MP, Camera trước: 32 MP, Ram: 8 GB, Bộ nhớ trong: 128 GB, Hổ trợ bộ nhớ ngoài tối đa 512 GB Dung lượng pin 3750 mAh",
                            ProductImage = "HN5T.jpg",
                            ProductName = "Huawei Nova 5T",
                            ProductPrice = 8990000.0,
                            ProductQuantity = 100
                        },
                        new
                        {
                            ProductId = 34,
                            CategoryId = 8,
                            CreateDate = new DateTime(2020, 12, 4, 0, 43, 44, 216, DateTimeKind.Local).AddTicks(5457),
                            Descriptions = "Công nghệ màn hình: LTPS, Độ phân giải: 	Full HD+ (720 x 1600 Pixels), Màn hình rộng: 6.51 inch, Mặt kính cảm ứng: 	Mặt kính cong 2.5D, Camera sau: 	Chính 13 MP & 2MP, Camera trước: 8 MP, Ram: 3 GB, Bộ nhớ trong: 32 GB, Hổ trợ bộ nhớ ngoài tối đa 256 GB Dung lượng pin 5000 mAh",
                            ProductImage = "VY12s.jpg",
                            ProductName = "Vivo Y12s",
                            ProductPrice = 3290000.0,
                            ProductQuantity = 100
                        },
                        new
                        {
                            ProductId = 35,
                            CategoryId = 8,
                            CreateDate = new DateTime(2020, 12, 4, 0, 43, 44, 216, DateTimeKind.Local).AddTicks(5459),
                            Descriptions = "Công nghệ màn hình: AMOLED, Độ phân giải: 	Full HD+ (1080 x 2376 Pixels), Màn hình rộng: 6.56 inch, Mặt kính cảm ứng: 	Kính cường lực Schott Xensation UP, Camera sau: Chính 48 MP & Phụ 13 MP, 8 MP, 8 MP, Camera trước: 32 MP, Ram: 8 GB, Bộ nhớ trong: 256 GB, Hổ trợ bộ nhớ ngoài tối đa 512 GB Dung lượng pin 4315 mAh",
                            ProductImage = "VYX50Pro.jpg",
                            ProductName = "Vivo X50 Pro",
                            ProductPrice = 18990000.0,
                            ProductQuantity = 100
                        },
                        new
                        {
                            ProductId = 36,
                            CategoryId = 8,
                            CreateDate = new DateTime(2020, 12, 4, 0, 43, 44, 216, DateTimeKind.Local).AddTicks(5461),
                            Descriptions = "Công nghệ màn hình: AMOLED, Độ phân giải: 	Full HD+ (1080 x 2400 Pixels), Màn hình rộng: 6.44 inch, Mặt kính cảm ứng: 	Kính cường lực Schott Xensation UP, Camera sau: Chính 48 MP & Phụ 13 MP, 2 MP, Camera trước: 32 MP, Ram: 8 GB, Bộ nhớ trong: 128 GB, Hổ trợ bộ nhớ ngoài tối đa 256 GB Dung lượng pin 4100 mAh",
                            ProductImage = "VYS20se.jpg",
                            ProductName = "Vivo V20 SE",
                            ProductPrice = 7190000.0,
                            ProductQuantity = 100
                        },
                        new
                        {
                            ProductId = 37,
                            CategoryId = 8,
                            CreateDate = new DateTime(2020, 12, 4, 0, 43, 44, 216, DateTimeKind.Local).AddTicks(5463),
                            Descriptions = "Công nghệ màn hình: IPS LCD, Độ phân giải: 	Full HD+ (720 x 1600 Pixels), Màn hình rộng: 6.51 inch, Mặt kính cảm ứng: 	Mặt kính cong 2.5D, Camera sau: Chính 13 MP & Phụ 2 MP, 2 MP, Camera trước: 8 MP, Ram: 6 GB, Bộ nhớ trong: 128 GB, Hổ trợ bộ nhớ ngoài tối đa 256 GB Dung lượng pin 5000 mAh",
                            ProductImage = "VY20s.jpg",
                            ProductName = "Vivo Y20s",
                            ProductPrice = 7190000.0,
                            ProductQuantity = 100
                        },
                        new
                        {
                            ProductId = 38,
                            CategoryId = 9,
                            CreateDate = new DateTime(2020, 12, 4, 0, 43, 44, 216, DateTimeKind.Local).AddTicks(5466),
                            Descriptions = "Độ phân giải: Full HD+(240 x 400 Pixels), Màn hình rộng: 2.8 inch, Bộ nhớ trong: Đang cập nhật,Thiết kế: Pin rời,Dung lượng pin 1000 mAh",
                            ProductImage = "LGE.jpg",
                            ProductName = "LG Extravert",
                            ProductPrice = 2500000.0,
                            ProductQuantity = 100
                        },
                        new
                        {
                            ProductId = 39,
                            CategoryId = 9,
                            CreateDate = new DateTime(2020, 12, 4, 0, 43, 44, 216, DateTimeKind.Local).AddTicks(5470),
                            Descriptions = "Màn hình:IPS LCD, 5.7Hệ điều hành:Android 10,Camera sau:Chính 13 MP & Phụ 5 MP,Camera trước:5 MP,CPU:MediaTek MT6762 8 nhân (Helio P22),RAM:3 GB,Bộ nhớ trong:32 GB,Thẻ nhớ:MicroSD,hỗ trợ tối đa 2 TB,Thẻ SIM:Hỗ trợ 4G,Dung lượng pin:3000 mAh",
                            ProductImage = "LG_Q31.png",
                            ProductName = "LG Q31",
                            ProductPrice = 7900000.0,
                            ProductQuantity = 100
                        },
                        new
                        {
                            ProductId = 40,
                            CategoryId = 9,
                            CreateDate = new DateTime(2020, 12, 4, 0, 43, 44, 216, DateTimeKind.Local).AddTicks(5472),
                            Descriptions = "Thiết Kế: Pin rời,Kích thước:102 x 45 x 20 mm,Trọng lượng: 79,Dung lượng pin:850 mAh",
                            ProductImage = "LG_G3000.png",
                            ProductName = "LG G3000",
                            ProductPrice = 350000.0,
                            ProductQuantity = 100
                        },
                        new
                        {
                            ProductId = 41,
                            CategoryId = 9,
                            CreateDate = new DateTime(2020, 12, 4, 0, 43, 44, 216, DateTimeKind.Local).AddTicks(5474),
                            Descriptions = "Màn hình:OLEDHệ điều hành:Android 8,Camera sau:16 MP Camera trước:8 MP,RAM:6 GB,Bộ nhớ trong:32 GB,Thẻ nhớ:MicroSD,hỗ trợ tối đa 2 TB,Dung lượng pin:3000 mAh",
                            ProductImage = "LG7.png",
                            ProductName = "LG G7",
                            ProductPrice = 6500000.0,
                            ProductQuantity = 100
                        },
                        new
                        {
                            ProductId = 42,
                            CategoryId = 4,
                            CreateDate = new DateTime(2020, 12, 4, 0, 43, 44, 216, DateTimeKind.Local).AddTicks(5476),
                            Descriptions = "Nokia 5310, Nghe, Gọi, Nhắn tin, Thay thế đồng hồ báo thức, Chống nước, Chống sốc",
                            ProductImage = "nokia 5310.jpg",
                            ProductName = "Nokia 5310",
                            ProductPrice = 1000000.0,
                            ProductQuantity = 100
                        },
                        new
                        {
                            ProductId = 43,
                            CategoryId = 1,
                            CreateDate = new DateTime(2020, 12, 4, 0, 43, 44, 216, DateTimeKind.Local).AddTicks(5478),
                            Descriptions = "Công nghệ màn hình: OLED, Độ phân giải: 1242 x 2688 Pixels, Màn hình rộng: 6.5 inch, Mặt kính cảm ứng: Kính cường lực oleophobic(ion cường lực), Camera sau: Độ phân giải 3 camera 12 MP, Camera trước: 12 MP, Ram: 4GB, Bộ nhớ trong: 64GB, Không hổ trợ bộ nhớ ngoàiDung lượng pin 3969 mAh",
                            ProductImage = "iphone12.jpeg",
                            ProductName = "Iphone12",
                            ProductPrice = 26000000.0,
                            ProductQuantity = 100
                        });
                });

            modelBuilder.Entity("PhoneWeb.Models.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedUserName")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("PhoneWeb.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("PhoneWeb.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PhoneWeb.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("PhoneWeb.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PhoneWeb.Models.Domain.OrderDetail", b =>
                {
                    b.HasOne("PhoneWeb.Models.Domain.Order", "Order")
                        .WithMany("OrderDetails")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PhoneWeb.Models.Domain.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PhoneWeb.Models.Domain.Product", b =>
                {
                    b.HasOne("PhoneWeb.Models.Domain.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
